include: package:flutter_lints/flutter.yaml

linter:
  rules:
    avoid_print: false
    prefer_const_constructors_in_immutables: true
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    prefer_final_fields: true
    unnecessary_breaks: true
    use_key_in_widget_constructors: false
    avoid_init_to_null : true
    avoid_redundant_argument_values : true
    avoid_returning_this : true
    avoid_single_cascade_in_expression_statements : true
    avoid_types_as_parameter_names : true
    avoid_unnecessary_containers : true
    avoid_unused_constructor_parameters : true
    avoid_void_async : true
    prefer_final_locals : true
    prefer_single_quotes : true
    annotate_overrides : true
    avoid_function_literals_in_foreach_calls : true
    unnecessary_null_aware_assignments: true
    prefer_final_parameters: true