import 'package:vego_flutter_project/diet_classes/diet_class.dart';
import 'package:flutter/material.dart';
import 'package:vego_flutter_project/global_widgets/barrel.dart';

class AdditiveFree extends PresetDiet {

  AdditiveFree()
      : super(
          name: 'Additive-Free',
          dietInfo: 'additive free',
          isProhibitive: true,
          isChecked: false,
          hidden: false,
          iconWidget: additiveFreeIcon(),
          primaryItems: prohibitedItemsList,
          secondaryItems: possiblyProhibitedItemsList,
        );

  static Widget additiveFreeIcon() {
    return dietIconWrapper(
      const Icon(
        Icons.science_outlined,
        color: Color.fromARGB(255, 140, 140, 140),
      ),
      true
    );//icons.bubble_chart
  }

  static List<String> prohibitedItemsList = [
    'Acacia Gum',
    'Acesulfame-potassium',
    'Acetic Acid',
    'Acetic Anhydride',
    'α-Acetolactate decarboxylase',
    'Acetone',
    'Acetone Peroxide',
    'Acetylated Monoglycerides',
    'Acetylated Tartaric Acid Esters of Mono and Di-Glycerides',
    'Adipic Acid',
    'Agar',
    'Algin',
    'Alginic Acid',
    'Alkanet',
    'Allura Red',
    'Alum',
    'Aluminum Metal',
    'Aluminum Ammonium Sulphate',
    'Aluminum Calcium Silicate',
    'Aluminum Potassium Sulphate',
    'Aluminum Sodium Sulphate',
    'Aluminum Sulphate',
    'Amaranth',
    'Aminopeptidase',
    'Ammonium Alginate',
    'Ammonium Aluminum Sulphate',
    'Ammonium Bicarbonate',
    'Ammonium Carbonate',
    'Ammonium Carrageenan',
    'Ammonium Chloride',
    'Ammonium Citrate, Mono and Dibasic',
    'Ammonium Furcelleran',
    'Ammonium Hydroxide',
    'Ammonium Persulphate',
    'Ammonium Phosphate, Mono and Dibasic',
    'Ammonium Salt of Phosphorylated Glyceride',
    'Ammonium Sulphate',
    'Amylase',
    'Amylase',
    'Amyloglucosidase',
    'Annatto',
    'Anthocyanins',
    "β-Apo-8'-Carotenal",
    'Arabinogalactan',
    'Ascorbic Acid',
    'Ascorbyl Palmitate',
    'Ascorbyl Stearate',
    'Aspartame',
    'Azodicarbonamide',
    "Baker's Yeast Glycan",
    'Beeswax',
    'Beet Red',
    'Benzoic Acid',
    'Benzoyl Peroxide',
    'Benzyl Alcohol',
    'BHA',
    'BHT',
    'Bovine Rennet',
    'Brillant Blue FCF',
    'Bromelain',
    'Brominated Vegetable Oil',
    'n-Butane',
    '2-Butanone',
    'Butylated Hydroxyanisole',
    'Butylated Hydroxytoluene',
    '1,3-Butylene Glycol',
    'Caffeine',
    'Caffeine Citrate',
    'Calcium Acetate',
    'Calcium Alginate',
    'Calcium Aluminum Silicate',
    'Calcium Ascorbate',
    'Calcium Carbonate',
    'Calcium Carrageenan',
    'Calcium Chloride',
    'Calcium Citrate',
    'Calcium Disodium EDTA',
    'Calcium Fumarate',
    'Calcium Furcelleran',
    'Calcium Gluconate',
    'Calcium Glycerophosphate',
    'Calcium Hydroxide',
    'Calcium Hypophosphite',
    'Calcium Iodate',
    'Calcium Lactate',
    'Calcium Oxide',
    'Calcium Peroxide',
    'Calcium Phosphate, Dibasic',
    'Calcium Phosphate, Monobasic',
    'Calcium Phosphate, Tribasic',
    'Calcium Phytate',
    'Calcium Propionate',
    'Calcium Silicate',
    'Calcium Sorbate',
    'Calcium Stearate',
    'Calcium Stearoyl-2-Lactylate',
    'Calcium Sulphate',
    'Calcium Tartrate',
    'Candelilla Wax',
    'Canthaxanthin',
    'Caramel',
    'Carbon Black',
    'Carbon Dioxide',
    'Carboxymethyl Cellulose',
    'Carnauba Wax',
    'Carob Bean Gum',
    'Carotene',
    'Carrageenan',
    'Castor Oil',
    'Catalase',
    'Cellulase',
    'Cellulose',
    'Cellulose Gum',
    'Cellulose, Microcrystalline',
    'Charcoal',
    'Chlorine',
    'Chlorine Dioxide',
    'Chloropentafluoroethane',
    'Chlorophyll',
    'Chymosin',
    'Citric Acid',
    'Citrus Red No.2',
    'Cochineal',
    'Copper Gluconate',
    'Cream of Tartar',
    'L-Cysteine',
    'Dicalcium Phosphate',
    'Dichloromethane',
    'Diglycerides',
    'Dimethylpolysiloxane Formulations',
    'Dioctylsodium Sulfo-Succinate',
    'Disodium Ethylenediaminetetraacetate',
    'Disodium Phosphate',
    'Epichlorohydrin',
    'Erythorbic Acid',
    'Erythritol',
    'Erythrosine',
    'Ethanol',
    'Ethoxyquin',
    'Ethyl Acetate',
    'Ethyl Alcohol',
    'Ethyl alcohol denatured with methanol',
    "Ethyl β-Apo-8'-carotenoate",
    'Ethylene Oxide',
    'Fast Green FCF',
    'Ferrous Gluconate',
    'Ferrous Sulphate',
    'Ficin',
    'Fumaric Acid',
    'Furcelleran',
    'Gelatin',
    'Gellan Gum',
    'Glucanase',
    'Glucoamylase',
    'Gluconic Acid',
    'Glucono delta lactone',
    'Glucose Isomerase',
    'Glucose Oxidase',
    'Glycerol',
    'Glycerol ester of wood rosin',
    'Glyceryl diacetate',
    'Glyceryl Monoacetate',
    'Glyceryl Triacetate',
    'Glyceryl Tributyrate',
    'Glycine',
    'Gold',
    'Guaiac Gum',
    'Guar Gum',
    'Gum Arabic',
    'Gum Benzoin',
    'Gum Guaiacum',
    'Gum Tragacanth',
    'Hemicellulase',
    'Hexane',
    '4-Hexylresorcinol',
    'Hydrochloric Acid',
    'Hydrogen Peroxide',
    'Hydrogenated starch hydrolysates',
    'Hydroxylated Lecithin',
    'Hydroxypropyl Cellulose',
    'Hydroxypropyl Methylcellulose',
    'Indigotine',
    'Inulinase',
    'Invertase',
    'Irish Moss Gelose',
    'Iron Oxide',
    'Isoascorbic Acid',
    'Isobutane',
    'Isomalt',
    'Isopropanol',
    'Isopropyl Alcohol',
    'Karaya Gum',
    'Lactase',
    'Lactic Acid',
    'Lactitol',
    'Lactylated Mono & Diglycerides',
    'Lactylic Esters of fatty acids',
    'Lanolin',
    'Lecithin',
    'Lecithin Citrate',
    'L-Cystein',
    'L-Leucine',
    'Lipase',
    'Lipoxidase',
    'Locust Bean Gum',
    'Lysozyme',
    'Magnesia',
    'Magnesium Aluminum Silicate',
    'Magnesium Carbonate',
    'Magnesium Chloride',
    'Magnesium Citrate',
    'Magnesium Fumarate',
    'Magnesium Hydroxide',
    'Magnesium Oxide',
    'Magnesium Phosphate',
    'Magnesium Silicate',
    'Magnesium Stearate',
    'Magnesium Sulphate',
    'Malic Acid',
    'Maltitol',
    'Manganese Sulphate',
    'Mannitol',
    'Methanol',
    'Methyl Alcohol',
    'Methylcellulose',
    'Methylene Chloride',
    'Methyl Ethyl Cellulose',
    'Methyl Ethyl Ketone',
    'Methyl-p-hydroxybenzoate',
    'Methyl Paraben',
    'Microcrystalline Cellulose',
    'Milk-coagulating enzyme',
    'Mineral Oil',
    'Monoacetin',
    'Monocalcium Phosphate',
    'Monoglycerides',
    'Mono- & Diglycerides',
    'Monoglyceride Citrate',
    'Monoisopropyl Citrate',
    'Monosodium Phosphate',
    'Monosodium salts of Phosphorylated Mono and Diglycerides',
    'Natamycin',
    'Nitric Acid',
    'Nitrogen',
    '2-Nitropropane',
    'Nitrous Oxide',
    'Oat Gum',
    'Octenyl Succinic Anhydride',
    'Octafluorocyclobutane',
    'Orchil',
    'Oxystearin',
    'Ozone',
    'Pancreas Extract',
    'Pancreatin',
    'Papain',
    'Paprika',
    'Paraffin Wax',
    'Pectin',
    'Pectinase',
    'Pentosanase',
    'Pepsin',
    'Peracetic Acid',
    'Petrolatum',
    'Phosphoric Acid',
    'Phosphorous Oxychloride',
    'Polydextrose',
    'Polyethylene glycol',
    'Polyglycerol Esters of Fatty Acid',
    'Polyglycerol Esters of Intersterified Castor Oil Fatty Acids',
    'Polyoxyethylene Sorbitan Monooleate',
    'Polyoxyethylene Sorbitan Monostearate',
    'Polyoxyethylene Sorbitan Tristearate',
    'Polyoxyethylene Stearate',
    'Polysorbate 60',
    'Polysorbate 65',
    'Polysorbate 80',
    'Polyvinylpyrrolidone',
    'Ponceau SX',
    'Potassium Acid Tartrate',
    'Potassium Alginate',
    'Potassium Aluminum Sulphate',
    'Potassium Benzoate',
    'Potassium Bicarbonate',
    'Potassium Bisulphite',
    'Potassium Bitartrate',
    'Potassium Carbonate',
    'Potassium Carrageenan',
    'Potassium Chloride',
    'Potassium Citrate',
    'Potassium Fumarate',
    'Potassium Furcelleran',
    'Potassium Hydroxide',
    'Potassium Iodate',
    'Potassium Lactate',
    'Potassium Metabisulphite',
    'Potassium Nitrate',
    'Potassium Nitrite',
    'Potassium Permanganate',
    'Potassium Persulphate',
    'Potassium Phosphate, Dibasic',
    'Potassium Phosphate, Monobasic',
    'Potassium Pyrophosphate, Tetrabasic',
    'Potassium Sodium Tartrate',
    'Potassium Sorbate',
    'Potassium Stearate',
    'Potassium Sulphate',
    'Potassium Tartrate',
    'Propane',
    'Propanediol',
    'Propionic Acid',
    'Propyl Gallate',
    'Propylene Glycol',
    'Propylene Glycol Alginate',
    'Propylene Glycol Ether of Methylcellulose',
    'Propylene Glycol Mono Fatty Acid Esters',
    'Propylene Glycol Monoesters and Diesters of fat-forming fatty acids',
    'Propylene Oxide',
    'Propyl-p-Hydroxy Benzoate',
    'Propyl Paraben',
    'Protease',
    'Pullulanase',
    'Quillaja Extract',
    'Rennet',
    'Riboflavin',
    'Saffron',
    'Saponin',
    'Saunders Wood',
    'Shellac',
    'Silicon Dioxide',
    'Silver Metal',
    'Sodium Acetate',
    'Sodium Acid Pyrophosphate',
    'Sodium Acid Tartrate',
    'Sodium Alginate',
    'Sodium Aluminum Phosphate',
    'Sodium Aluminum Silicate',
    'Sodium Aluminum Sulphate',
    'Sodium Ascorbate',
    'Sodium Benzoate',
    'Sodium Bicarbonate',
    'Sodium Bisulphate',
    'Sodium Bisulphite',
    'Sodium Carbonate',
    'Sodium Carboxymethyl Cellulose',
    'Sodium Carrageenan',
    'Sodium Cellulose Glycolate',
    'Sodium Chlorite',
    'Sodium Citrate',
    'Sodium Diacetate',
    'Sodium Dithionite',
    'Sodium Erythorbate',
    'Sodium Ferrocyanide, Decahydrate',
    'Sodium Fumarate',
    'Sodium Furcelleran',
    'Sodium Gluconate',
    'Sodium Hexametaphosphate',
    'Sodium Hydroxide',
    'Sodium Hypochlorite',
    'Sodium Isoascorbate',
    'Sodium Lactate',
    'Sodium Lauryl Sulphate',
    'Sodium Metabisulphite',
    'Sodium Methyl Sulphate',
    'Sodium Nitrate',
    'Sodium Nitrite',
    'Sodium Phosphate, Dibasic',
    'Sodium Phosphate, Monobasic',
    'Sodium Phosphate, Tribasic',
    'Sodium Potassium Copper Chlorophyllin',
    'Sodium Potassium Tartrate',
    'Sodium Propionate',
    'Sodium Pyrophosphate, tetrabasic',
    'Sodium Salt of Methyl-p-Hydroxy Benzoic Acid',
    'Sodium Salt of Propyl-p-Hydroxy Benzoic Acid',
    'Sodium Silicate',
    'Sodium Sorbate',
    'Sodium Stearate',
    'Sodium Stearyl Fumarate',
    'Sodium Stearoyl-2-Lactylate',
    'Sodium Sulphate',
    'Sodium Sulphite',
    'Sodium Tartrate',
    'Sodium Thiosulphate',
    'Sodium Trimetaphosphate',
    'Sodium Tripolyphosphate',
    'Sorbic Acid',
    'Sorbitan Monostearate',
    'Sorbitan Trioleate',
    'Sorbitan Tristearate',
    'Sorbitol',
    'Spermaceti Wax',
    'Stannous Chloride',
    'Stearic Acid',
    'Stearyl Citrate',
    'Stearyl Monoglyceridyl Citrate',
    'Succinic Anhydride',
    'Sucralose',
    'Sucrose Acetate Isobutyrate',
    'Sucrose esters of fatty acids',
    'Sulphur Dioxide',
    'Sulphuric Acid',
    'Sulphurous Acid',
    'Sunset Yellow FCF',
    'Talc',
    'Tannic Acid',
    'Tartaric Acid',
    'Tartrazine',
    'Tertiary Butyl Hydroquinone',
    'Tetrasodium Diphosphate',
    'Tetrasodium Pyrophosphate',
    'Thaumatin',
    'Titanium Dioxide',
    'Tocopherols',
    'Tragacanth Gum',
    'Transglutaminase',
    'Triacetin',
    'Tributyrin',
    'Tricalcium Phosphate',
    'Triethyl Citrate',
    'Trisodium Phosphate',
    'Trypsin',
    'Turmeric',
    'Wood Smoke',
    'Xanthan Gum',
    'Xanthophyll',
    'Xylanase',
    'Xylitol',
    'Zein',
    'Zinc Sulphate'
  ];
  static List<String> possiblyProhibitedItemsList = [

  ];
}