export 'package:vego_flutter_project/global_widgets/text_field.dart';
export 'package:vego_flutter_project/global_widgets/divider.dart';
export 'package:vego_flutter_project/global_widgets/cards.dart';
export 'package:vego_flutter_project/global_widgets/platform_management.dart';
export 'package:vego_flutter_project/global_widgets/button.dart';
export 'package:vego_flutter_project/global_widgets/info_slider.dart';
export 'package:vego_flutter_project/global_widgets/navigation_bar.dart';
export 'package:vego_flutter_project/global_widgets/icon_wrapper.dart';
export 'package:vego_flutter_project/global_widgets/build_diet_info.dart';